### ISSUE TITLE
Change function submitRing's visibility to external

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#152]
Currently it is 'public', changing it to 'externa'l will avoid copying argument data to save some gas.

**Comment by dong77** [comment]
I'm getting this error after the change.

```

/Users/d/Projects/loopring/protocol/contracts/LoopringProtocolImpl.sol:224:25: CompilerError: Stack too deep, try removing local variables.
        uint ringSize = addressList.length;

```

Don't know how to resolve. Need some help from the community.

**Comment by Brechtpd** [comment]
The different behaviour between public and external seems to be that array parameters in external functions take up 2 slots on the stack instead of 1 for public functions. 

I'm not convinced this is going this save any gas, at least not in the way the data is used now. All arrays are passed to internal functions, which need all data to be in memory. So I don't think there's going to be a case where data would only be read from the calldata. Though if more functionality is placed inside the submitRing function it could help I suppose.

**Comment by dong77** [comment]
Thank you. I'm not sure about if there is any gas savings but what makes me curious is why it doesn't compile when I change it form `public` to `external`. Maybe because ` array parameters in external functions take up 2 slots on the stack instead of 1 for public functions.`?

**Comment by Brechtpd** [comment]
Yeah, that's right. That's the behaviour I see by experimenting a bit. I did not find anything yet in the documentation nor have i checked the assembly. I'll get back to you on this if I find out exactly why the extra stack space is needed.

**Comment by Brechtpd** [comment]
There's a limit of 16 local variables on the stack.

**Comment by dong77** [comment]
But I didn't introduce addition local variables...

**Comment by Brechtpd** [comment]
Local variables also include function arguments and return values. A bit confusing, I know, but that's how everyone seems to define it. Probably doesn't matter for Solidity what type of variable it is, they all get pushed on the stack.
