### ISSUE TITLE
Reentry attack possible after pull request #289

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocol#290]
ringIndex is updated with ENTERED_MASK in MEMORY, not in STORAGE. So ENTERED_MASK isn't set when loading ringIndex in a reentry scenario.

This is a major security issue.

This was introduced in pull request #289.

**Comment by Brechtpd** [comment]
I think you misunderstood the problem. To make it more clear this:
`_ringIndex |= ENTERED_MASK;`
NEEDS to be changed to
`ringIndex |= ENTERED_MASK;`
for the reentry detection to work. The storage variable needs to be updated so that if the function is called again ringIndex is loaded with ENTERED_MASK set.

**Comment by Brechtpd** [comment]
I've been thinking about this a bit more. Maybe (and I say maybe, I'm not an expert in this) the mutex could be removed. Though with an additional change.

There's not a lot of storage actually used in submitRing that is updated. Only ringIndex and cancelledOrFilled. All other data is passed in as parameters. If it's ensured that ringIndex is updated before any externall calls I think it should work fine. 
cancelOrder currently doesn't check the mutex so the function is in theory vulnerable to exploitation, but because it only modifies cancelled and cancelledOrFilled I don't think you can abuse it (though I could be wrong, cancelledOrFilled is used in submitRing so it can impact how submitRing functions).

**Comment by Brechtpd** [comment]
I think I found an attack case that shows a mutex is indeed needed for submitRing:
- submitRing() is called for a ring
- scaleRingBasedOnHistoricalRecords() is called, which uses cancelledOrFilled to make sure not more tokens are traded than requested
- calculateRingFees() is called afterwards and does external calls (though to the LRC token contract)
- settleRing() is called afterwards updating cancelledOrFilled

The external calls in calculateRingFees() could call submitRing() using the same ring parameters. This reentry call would call scaleRingBasedOnHistoricalRecords() without the updated cancelledOrFilled amounts. This would allow the same trades to be executed multiple times.

Though you could argue the external calls in calculateRingFees() should happen on the LRC contract, so could be deemed safe.

**Comment by Hephyrius** [comment]
I've been trying to think up how ring Index would make the contract open to a reentry attack and I really can't think up any cases, the ring index itself is used as a logging mechanism and stored within the log storage of the contract on the blockchain, so that it can be looked at - such as via a loop explorer . The only instance I can think of where this would be an issue is where two contracts are being run at the same time, as this would result in the contracts having the same logged loop index. would be akin to an multithread problem in a regular program when locking isn't don't right.

Incrementing in the manner you propose would avoid having more than one ringIndex of the same value to be stored on the blockchain.

**Comment by Brechtpd** [comment]
Yeah, that's correct. If that would be the only problem by a not working mutex that wouldn't be that big of a problem. Though the question is IF that's the only possible problem (see possible attack explained above). There was that security audit by Berkeley and it's not like they said the mutex wasn't needed (the scope of the audit contained 'Reentrancy attacks').
